[package]
name = "keccack"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
sp1-zkvm = { workspace = true }
sp1-sdk = { workspace = true }
tiny-keccak = { workspace = true }
rand = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
