[package]
name = "p256"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
sp1-zkvm = { workspace = true }
p256 = { workspace = true }
hex-literal = { workspace = true }
