[package]
name = "p256"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "p256_low_sig_recovery"
path = "bin/low_sig_recovery.rs"
description = "Test a p256 low signature recovery"

[[bin]]
name = "p256_high_sig_recovery"
path = "bin/high_sig_recovery.rs"
description = "Test a p256 high signature recovery"

[[bin]]
name = "p256_low_sig_verify"
path = "bin/low_sig_verify.rs"
description = "Test a p256 low signature verification"

[[bin]]
name = "p256_high_sig_verify"
path = "bin/high_sig_verify.rs"
description = "Test a p256 high signature verification"

[dependencies]
sp1-zkvm = { workspace = true }
p256 = { workspace = true }
hex-literal = { workspace = true }
ecdsa-core = { workspace = true }
