[package]
name = "curve25519-dalek-ng"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
curve25519-dalek-ng = { workspace = true }
hex-literal = { workspace = true }
sp1-zkvm = { workspace = true }
