[package]
name = "secp256k1"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "secp256k1_recover"
path = "bin/recover.rs"

[[bin]]
name = "secp256k1_recover_fail"
path = "bin/recover_fail.rs"

[[bin]]
name = "secp256k1_verify"
path = "bin/verify.rs"

[[bin]]
name = "secp256k1_verify_fail"
path = "bin/verify_fail.rs"

[dependencies]
sp1-zkvm = { workspace = true }
secp256k1 = { workspace = true }
hex-literal = { workspace = true }
hex = "0.4.3"
