[package]
name = "sp1-recursion-static-program"
version = "0.0.2-test"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
bincode = "1.3.3"
p3-baby-bear = { workspace = true }
sp1-recursion-core = { path = "../core" }
sp1-core = { path = "../../core" }
paste = "1.0.15"

[build-dependencies]
sp1-recursion-program = { path = "../program" }
sp1-recursion-compiler = { path = "../compiler" }
sp1-recursion-core = { path = "../core" }
sp1-core = { path = "../../core" }
sp1-primitives = { path = "../../primitives" }
p3-baby-bear = { workspace = true }
bincode = "1.3.3"
