[package]
name = "sp1-precompiles"
version = "0.1.0"
edition = "2021"

[dependencies]
amcl = { package = "snowbridge-amcl", version = "1.0.2", default-features = false, features = [
  "bls381",
], optional = true }
anyhow = { version = "1.0.83", optional = true }
bincode = "1.3.3"
cfg-if = { version = "1.0.0", optional = true }
getrandom = { version = "0.2.14", features = ["custom"], optional = true }
hex = { version = "0.4.3", optional = true }
k256 = { version = "0.13.3", features = [
  "ecdsa",
  "std",
  "bits",
], optional = true }
rand = { version = "0.8.5", optional = true }
serde = { version = "1.0.201", features = ["derive"] }
num = { version = "0.4.3", optional = true }

[features]
verify = []
bls = ["dep:amcl", "dep:k256", "dep:getrandom", "dep:rand"]
