[package]
name = "sp1-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
bincode = "1.3.3"
cfg-if = "1.0.0"
serde = { version = "1.0.201", features = ["derive"] }

# Used for bls12381 feature
amcl = { package = "snowbridge-amcl", version = "1.0.2", default-features = false, features = [
  "bls381",
], optional = true }
hex = { version = "0.4.3", optional = true }

# Used for k256 feature
k256 = { version = "0.13.3", features = ["ecdsa", "std", "bits"], optional = true }

[features]
default = ["bn254", "k256", "bls12381"]
verify = []
bn254 = []
k256 = ["dep:k256"]
bls12381 = ["dep:amcl", "dep:hex"]