[workspace]
members = [
  "build",
  "cli",
  "core",
  "derive",
  "eval",
  "helper",
  "primitives",
  "prover",
  "recursion/circuit",
  "recursion/circuit-v2",
  "recursion/compiler",
  "recursion/core",
  "recursion/core-v2",
  "recursion/derive",
  "recursion/gnark-cli",
  "recursion/gnark-ffi",
  "recursion/program",
  "sdk",
  "zkvm/*",
]
exclude = ["examples/target"]
resolver = "2"

[workspace.package]
version = "1.0.0-rc.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/succinctlabs/sp1"
keywords = ["sp1", "succinct", "zero-knowledge", "zkvm"]
categories = ["cryptography"]

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3

[profile.fast]
inherits = "release"
debug = true
debug-assertions = true

[workspace.dependencies]
sp1-build = { path = "build", version = "1.0.0-rc.1" }
sp1-derive = { path = "derive", version = "1.0.0-rc.1" }
sp1-core = { path = "core", version = "1.0.0-rc.1" }
sp1-cli = { path = "cli", version = "1.0.0-rc.1", default-features = false }
sp1-eval = { path = "eval", version = "1.0.0-rc.1", default-features = false }
sp1-helper = { path = "helper", version = "1.0.0-rc.1", default-features = false }
sp1-primitives = { path = "primitives", version = "1.0.0-rc.1" }
sp1-prover = { path = "prover", version = "1.0.0-rc.1" }
sp1-recursion-compiler = { path = "recursion/compiler", version = "1.0.0-rc.1" }
sp1-recursion-core = { path = "recursion/core", version = "1.0.0-rc.1", default-features = false }
sp1-recursion-core-v2 = { path = "recursion/core-v2", version = "1.0.0-rc.1", default-features = false }
sp1-recursion-derive = { path = "recursion/derive", version = "1.0.0-rc.1", default-features = false }
sp1-recursion-gnark-ffi = { path = "recursion/gnark-ffi", version = "1.0.0-rc.1", default-features = false }
sp1-recursion-program = { path = "recursion/program", version = "1.0.0-rc.1", default-features = false }
sp1-recursion-circuit = { path = "recursion/circuit", version = "1.0.0-rc.1", default-features = false }
sp1-recursion-circuit-v2 = { path = "recursion/circuit-v2", version = "1.0.0-rc.1", default-features = false }
sp1-sdk = { path = "sdk", version = "1.0.0-rc.1" }
sp1-lib = { path = "zkvm/lib", version = "1.0.0-rc.1", default-features = false }
sp1-zkvm = { path = "zkvm/entrypoint", version = "1.0.0-rc.1", default-features = false }
p3-air = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-field = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-commit = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-matrix = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-baby-bear = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9", features = ["nightly-features"] }
p3-util = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-challenger = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-dft = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-fri = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-goldilocks = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-keccak = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-keccak-air = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-blake3 = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-mds = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-merkle-tree = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-poseidon2 = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-symmetric = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-uni-stark = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-maybe-rayon = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}
p3-bn254-fr = {git = "https://github.com/Plonky3/Plonky3.git", rev = "5616883de57c9ac40d970d087caed8ebbcf616f9"}

# For local development. 

# p3-air = { path = "../my_p3_fork/Plonky3/air" }
# p3-field = { path = "../my_p3_fork/Plonky3/field" }
# p3-commit = { path = "../my_p3_fork/Plonky3/commit" }
# p3-matrix = { path = "../my_p3_fork/Plonky3/matrix" }
# p3-baby-bear = { path = "../my_p3_fork/Plonky3/baby-bear" }
# p3-util = { path = "../my_p3_fork/Plonky3/util" }
# p3-challenger = { path = "../my_p3_fork/Plonky3/challenger" }
# p3-dft = { path = "../my_p3_fork/Plonky3/dft" }
# p3-fri = { path = "../my_p3_fork/Plonky3/fri" }
# p3-goldilocks = { path = "../my_p3_fork/Plonky3/goldilocks" }
# p3-keccak = { path = "../my_p3_fork/Plonky3/keccak" }
# p3-keccak-air = { path = "../my_p3_fork/Plonky3/keccak-air" }
# p3-blake3 = { path = "../my_p3_fork/Plonky3/blake3" }
# p3-mds = { path = "../my_p3_fork/Plonky3/mds" }
# p3-merkle-tree = { path = "../my_p3_fork/Plonky3/merkle-tree" }
# p3-poseidon2 = { path = "../my_p3_fork/Plonky3/poseidon2" }
# p3-symmetric = { path = "../my_p3_fork/Plonky3/symmetric" }
# p3-uni-stark = { path = "../my_p3_fork/Plonky3/uni-stark" }
# p3-maybe-rayon = { path = "../my_p3_fork/Plonky3/maybe-rayon" }
# p3-bn254-fr = { path = "../my_p3_fork/Plonky3/bn254-fr" }
