[workspace.package]
version = "1.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/succinctlabs/sp1"
keywords = ["sp1", "succinct", "zero-knowledge", "zkvm"]
categories = ["cryptography"]

[workspace]
members = [
  "crates/build",
  "crates/cli",
  "crates/core/executor",
  "crates/core/machine",
  "crates/curves",
  "crates/derive",
  "crates/helper",
  "crates/primitives",
  "crates/prover",
  "crates/recursion/circuit",
  "crates/recursion/circuit-v2",
  "crates/recursion/compiler",
  "crates/recursion/core",
  "crates/recursion/core-v2",
  "crates/recursion/derive",
  "crates/recursion/gnark-cli",
  "crates/recursion/gnark-ffi",
  "crates/recursion/program",
  "crates/sdk",
  "crates/cuda",
  "crates/stark",
  "crates/zkvm/*",
]
exclude = ["examples/target"]
resolver = "2"

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3

[profile.fast]
inherits = "release"
debug = true
debug-assertions = true

[workspace.dependencies]
# sp1
sp1-build = { path = "crates/build", version = "1.1.1" }
sp1-core-machine = { path = "crates/core/machine", version = "1.1.1" }
sp1-core-executor = { path = "crates/core/executor", version = "1.1.1" }
sp1-derive = { path = "crates/derive", version = "1.1.1" }
sp1-cli = { path = "crates/cli", version = "1.1.1", default-features = false }
sp1-curves = { path = "crates/curves", version = "1.1.1" }
sp1-helper = { path = "crates/helper", version = "1.1.1", default-features = false }
sp1-primitives = { path = "crates/primitives", version = "1.1.1" }
sp1-prover = { path = "crates/prover", version = "1.1.1" }
sp1-recursion-compiler = { path = "crates/recursion/compiler", version = "1.1.1" }
sp1-recursion-core = { path = "crates/recursion/core", version = "1.1.1", default-features = false }
sp1-recursion-core-v2 = { path = "crates/recursion/core-v2", version = "1.1.1", default-features = false }
sp1-recursion-derive = { path = "crates/recursion/derive", version = "1.1.1", default-features = false }
sp1-recursion-gnark-ffi = { path = "crates/recursion/gnark-ffi", version = "1.1.1", default-features = false }
sp1-recursion-program = { path = "crates/recursion/program", version = "1.1.1", default-features = false }
sp1-recursion-circuit = { path = "crates/recursion/circuit", version = "1.1.1", default-features = false }
sp1-sdk = { path = "crates/sdk", version = "1.1.1" }
sp1-cuda = { path = "crates/cuda", version = "1.1.1" }
sp1-stark = { path = "crates/stark", version = "1.1.1" }
sp1-lib = { path = "crates/zkvm/lib", version = "1.1.1", default-features = false }
sp1-zkvm = { path = "crates/zkvm/entrypoint", version = "1.1.1", default-features = false }

# p3
# p3-air = "0.1.3-succinct"
# p3-field = "0.1.3-succinct"
# p3-commit = "0.1.3-succinct"
# p3-matrix = "0.1.3-succinct"
# p3-baby-bear = { version = "0.1.3-succinct", features = ["nightly-features"] }
# p3-util = "0.1.3-succinct"
# p3-challenger = "0.1.3-succinct"
# p3-dft = "0.1.3-succinct"
# p3-fri = "0.1.3-succinct"
# p3-goldilocks = "0.1.3-succinct"
# p3-keccak = "0.1.3-succinct"
# p3-keccak-air = "0.1.3-succinct"
# p3-blake3 = "0.1.3-succinct"
# p3-mds = "0.1.3-succinct"
# p3-merkle-tree = "0.1.3-succinct"
# p3-poseidon2 = "0.1.3-succinct"
# p3-symmetric = "0.1.3-succinct"
# p3-uni-stark = "0.1.3-succinct"
# p3-maybe-rayon = "0.1.3-succinct"
# p3-bn254-fr = "0.1.3-succinct"

# For local development. 

p3-air = { path = "../my_p3_fork/Plonky3/air" }
p3-field = { path = "../my_p3_fork/Plonky3/field" }
p3-commit = { path = "../my_p3_fork/Plonky3/commit" }
p3-matrix = { path = "../my_p3_fork/Plonky3/matrix" }
p3-baby-bear = { path = "../my_p3_fork/Plonky3/baby-bear" }
p3-util = { path = "../my_p3_fork/Plonky3/util" }
p3-challenger = { path = "../my_p3_fork/Plonky3/challenger" }
p3-dft = { path = "../my_p3_fork/Plonky3/dft" }
p3-fri = { path = "../my_p3_fork/Plonky3/fri" }
p3-goldilocks = { path = "../my_p3_fork/Plonky3/goldilocks" }
p3-keccak = { path = "../my_p3_fork/Plonky3/keccak" }
p3-keccak-air = { path = "../my_p3_fork/Plonky3/keccak-air" }
p3-blake3 = { path = "../my_p3_fork/Plonky3/blake3" }
p3-mds = { path = "../my_p3_fork/Plonky3/mds" }
p3-merkle-tree = { path = "../my_p3_fork/Plonky3/merkle-tree" }
p3-poseidon2 = { path = "../my_p3_fork/Plonky3/poseidon2" }
p3-symmetric = { path = "../my_p3_fork/Plonky3/symmetric" }
p3-uni-stark = { path = "../my_p3_fork/Plonky3/uni-stark" }
p3-maybe-rayon = { path = "../my_p3_fork/Plonky3/maybe-rayon" }
p3-bn254-fr = { path = "../my_p3_fork/Plonky3/bn254-fr" }
