[package]
name = "fibonacci-script"
version = { workspace = true }
edition = { workspace = true }
default-run = "fibonacci-script"
publish = false

[dependencies]
sp1-sdk = { workspace = true, features = ["blocking"] }

hex = "0.4.3"
tokio = { version = "1.0", features = ["full", "macros"] }
futures = "0.3"
dotenv = "0.15"

[build-dependencies]
sp1-build = { workspace = true }

[[bin]]
name = "plonk_bn254"
path = "bin/plonk_bn254.rs"

[[bin]]
name = "groth16_bn254"
path = "bin/groth16_bn254.rs"

[[bin]]
name = "compressed"
path = "bin/compressed.rs"

[[bin]]
name = "execute"
path = "bin/execute.rs"

[[bin]]
name = "network"
path = "bin/network.rs"

[[bin]]
name = "fibonacci-script"
path = "src/main.rs"

[features]
cuda = ["sp1-sdk/cuda"]
