[package]
name = "sp1-zkvm"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
getrandom = { version = "0.2.14", features = ["custom"] }
rand = "0.8.5"
libm = { version = "0.2.8", optional = true }
sha2 = { version = "0.10.8" }
lazy_static = "1.5.0"

# Used for verify feature
sp1-primitives = { path = "../../primitives", optional = true }
p3-baby-bear = { workspace = true, optional = true }
p3-field = { workspace = true, optional = true }

[features]
default = ["libm"]
libm = ["dep:libm"]
verify = [
  "dep:sp1-primitives",
  "dep:p3-baby-bear",
  "dep:p3-field",
]
