[package]
name = "sha"
version.workspace = true
edition.workspace = true
publish.workspace = true
members.workspace = true

[dependencies]
sp1-zkvm = { workspace = true }
sha2-v0-9-8 = { workspace = true }
sha2-v0-10-6 = { workspace = true }
hex-literal = { workspace = true }
