[package]
name = "ed25519-dalek"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
ed25519-dalek = { workspace = true }
hex-literal = { workspace = true }
sp1-zkvm = { workspace = true }
