[package]
name = "ed25519-dalek"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "ed25519_verify"
path = "bin/verify.rs"

[[bin]]
name = "curve25519_decompress_fail"
path = "bin/decompress_fail.rs"

[dependencies]
curve25519-dalek = { workspace = true }
ed25519-dalek = { workspace = true }
hex-literal = { workspace = true }
sp1-zkvm = { workspace = true }
