[package]
name = "rsa-script"
version = "1.0.0-rc.1"
edition = "2021"
publish = false

[dependencies]
rsa = "0.6"
sp1-sdk = { workspace = true }

[build-dependencies]
sp1-helper = { workspace = true }
