[workspace]
[package]
name = "rsa-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../crates/zkvm/entrypoint" }
digest = "0.10.7"
rand = "0.8.5"
rsa = { path = "../../../../new_RSA" }                            # Check for the latest version
sha2 = {version =  "=0.11.0-pre.4",package = "sha2", features = ["oid"]}                                  # Check for the latest version
# hybrid-array = "0.1.0" 
# [patch.crates-io]
# # Patch sha2 so we can use sha precompiles
# sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.10.8"}

