[package]
name = "rsa-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../crates/zkvm/entrypoint" }
rsa = { git = "https://github.com/sp1-patches/RustCrypto-RSA", branch = "patch-rsa-v0.9.6" }                                  # Check for the latest version
sha2 = {version =  "0.10.8",package = "sha2", features = ["oid"]}                                   # Check for the latest version
