[package]
name = "io-script"
version = "1.0.0-rc.1"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
sp1-sdk = { workspace = true }

[build-dependencies]
sp1-helper = { workspace = true }
