[package]
name = "keccack"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
sp1-zkvm = { workspace = true }
tiny-keccak = { workspace = true }
hex-literal = { workspace = true }
