[workspace]
[package]
name = "bls12381"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../crates/zkvm/entrypoint" }
num = { version = "0.4.1", default-features = false }
serde_yaml = "0.9.34"
kzg-rs = { git = "https://github.com/succinctlabs/kzg-rs", branch = "bhargav/sp1-bls-patch"}
serde = "1.0.208"
