[package]
name = "ed25519-consensus"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
ed25519-consensus = { workspace = true }
sp1-zkvm = { workspace = true }
hex-literal = { workspace = true }
