name: PR

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"
    paths:
      - "cli/**"
      - "core/**"
      - "prover/**"
      - "recursion/**"
      - "derive/**"
      - "sdk/**"
      - "zkvm/**"
      - "tests/**"
      - "examples/**"
      - "Cargo.toml"
      - ".github/workflows/**"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-x86:
    name: Test (x86-64)
    runs-on: runs-on,runner=64cpu-linux-x64,spot=false
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          toolchain: nightly-2024-04-17
          args: --all-targets --all-features

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: nightly-2024-04-17
          args: --release --features native-gnark
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0 -C target-cpu=native
          RUST_BACKTRACE: 1
          FRI_QUERIES: 1
          SP1_DEV: 1

  test-arm:
    name: Test (ARM)
    runs-on: runs-on,runner=64cpu-linux-arm64,spot=false
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          toolchain: nightly-2024-04-17
          args: --all-targets --all-features

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: nightly-2024-04-17
          args: --release --features native-gnark
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0 -C target-cpu=native
          RUST_BACKTRACE: 1
          FRI_QUERIES: 1
          SP1_DEV: 1

  lint:
    name: Formatting & Clippy
    runs-on: runs-on,runner=8cpu-linux-x64
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        env:
          CARGO_INCREMENTAL: 1

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings -A incomplete-features
        env:
          CARGO_INCREMENTAL: 1

  examples-base:
    name: Examples (baseline)
    runs-on: runs-on,runner=8cpu-linux-x64
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
            ref: igor/bench # TODO: change to main

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version

      - name: Install SP1 CLI
        run: |
          cd cli
          cargo install --force --locked --path .
          ~/.sp1/bin/cargo-prove prove install-toolchain
          cd ~

      - name: Run cargo check
        run: |
          RUSTFLAGS="-Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0 -C target-cpu=native" \
          cargo check --manifest-path examples/Cargo.toml --all-targets --all-features

      - name: Run benchmark
        run: cargo run --manifest-path examples/Cargo.toml --release --bin bench-fibonacci -- run benchmark_base.json
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0 -C target-cpu=native
          RUST_BACKTRACE: 1
          FRI_QUERIES: 1
          SP1_DEV: 1

      - name: Upload benchmark result
        uses: actions/upload-artifact@v4
        with:
          name: benchmark_base.json
          path: benchmark_base.json
          if-no-files-found: error

  examples-head:
    name: Examples
    runs-on: runs-on,runner=8cpu-linux-x64
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version

      - name: Install SP1 CLI
        run: |
          cd cli
          cargo install --force --locked --path .
          ~/.sp1/bin/cargo-prove prove install-toolchain
          cd ~

      - name: Run cargo check
        run: |
          RUSTFLAGS="-Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0 -C target-cpu=native" \
          cargo check --manifest-path examples/Cargo.toml --all-targets --all-features

      - name: Run benchmark
        run: cargo run --manifest-path examples/Cargo.toml --release --bin bench-fibonacci -- run benchmark_head.json
        env:
          RUSTFLAGS: -Copt-level=3 -Cdebug-assertions -Coverflow-checks=y -Cdebuginfo=0 -C target-cpu=native
          RUST_BACKTRACE: 1
          FRI_QUERIES: 1
          SP1_DEV: 1

      - name: Upload benchmark result
        uses: actions/upload-artifact@v4
        with:
          name: benchmark_head.json
          path: benchmark_head.json
          if-no-files-found: error

  examples-benchmark:
    name: Examples (benchmark)
    needs: [examples-head, examples-base]
    runs-on: runs-on,runner=8cpu-linux-x64
    permissions:
      pull-requests: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version

      - name: Install SP1 CLI
        run: |
          cd cli
          cargo install --force --locked --path .
          ~/.sp1/bin/cargo-prove prove install-toolchain
          cd ~

      - name: Download result examples
        uses: actions/download-artifact@v4
        with:
          name: benchmark_head.json

      - name: Download result examples-base
        uses: actions/download-artifact@v4
        with:
          name: benchmark_base.json

      - name: Run benchmark comparison
        run: |
          cargo run --manifest-path examples/Cargo.toml --release --bin bench-fibonacci -- compare benchmark_base.json benchmark_head.json | tee result.txt

      - name: Comment PR
        uses: mshick/add-pr-comment@v2
        with:
          message-path: result.txt

  cli:
    name: CLI
    runs-on: runs-on,runner=8cpu-linux-x64
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version

      - name: Install SP1 CLI
        run: |
          cd cli
          cargo install --force --locked --path .
          cd ~

      - name: Run cargo prove new
        run: |
          cargo prove new fibonacci --version dev

      - name: Build program and run script
        run: |
          cd fibonacci
          cd program
          cargo add sp1-zkvm --path $GITHUB_WORKSPACE/zkvm/entrypoint
          cargo prove build
          cd ../script
          cargo remove sp1-sdk
          cargo add sp1-sdk --path $GITHUB_WORKSPACE/sdk
          SP1_DEV=1 RUST_LOG=info cargo run --release
