name: checks
run-name: Execution precheckin for change by ${{ github.actor }}
on:
  pull_request:
  push:
    branches:
      - chris/test-ci

jobs:
  test-prove:
    runs-on: ubuntu-22.04
    steps:
      - name: Install SP1
        run: |
          curl -L https://sp1.succinct.xyz | bash
          export SP1_DIR=${XDG_CONFIG_HOME:-$HOME}/.sp1
          echo "SP1_DIR=$SP1_DIR" >> $GITHUB_ENV
          $SP1_DIR/bin/sp1up
          $SP1_DIR/bin/cargo-prove prove --version
